markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Andrew Collord
url: http://collord.org
description: A fantastic blog that is fantastic.
# twitter: holman
