markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Andrew Collord
url: http://collord.org
description: A website about everyone's favorite topic
# twitter: holman
